import { fetchChelseaSquad, transformPlayer } from './footballApi';

export interface Player {
  id: number;
  name: string;
  position: string;
  nationality: string;
  photo_url?: string;
  number?: number;
  age?: number;
  height?: string;
  weight?: string;
  goals?: number;
  assists?: number;
  appearances?: number;
  rating?: string;
  created_at: string;
}

// Fallback Chelsea squad data (2024/25 season - current squad)
const FALLBACK_SQUAD: Player[] = [
  {
    id: 1,
    name: "Đorđe Petrović",
    position: "Goalkeeper",
    nationality: "Serbia",
    photo_url: "/chelsea-logo.png",
    number: 1,
    age: 24,
    height: "194cm",
    weight: "88kg",
    goals: 0,
    assists: 0,
    appearances: 15,
    rating: "7.1",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Axel Disasi",
    position: "Defender",
    nationality: "France",
    photo_url: "/chelsea-logo.png",
    number: 2,
    age: 25,
    height: "190cm",
    weight: "85kg",
    goals: 1,
    assists: 0,
    appearances: 18,
    rating: "6.8",
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Marc Cucurella",
    position: "Defender",
    nationality: "Spain",
    photo_url: "/chelsea-logo.png",
    number: 3,
    age: 25,
    height: "175cm",
    weight: "72kg",
    goals: 0,
    assists: 2,
    appearances: 12,
    rating: "6.9",
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Benoît Badiashile",
    position: "Defender",
    nationality: "France",
    photo_url: "/chelsea-logo.png",
    number: 4,
    age: 22,
    height: "194cm",
    weight: "85kg",
    goals: 0,
    assists: 0,
    appearances: 8,
    rating: "6.7",
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Enzo Fernández",
    position: "Midfielder",
    nationality: "Argentina",
    photo_url: "/chelsea-logo.png",
    number: 5,
    age: 23,
    height: "178cm",
    weight: "77kg",
    goals: 3,
    assists: 7,
    appearances: 25,
    rating: "7.2",
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Cole Palmer",
    position: "Midfielder",
    nationality: "England",
    photo_url: "/chelsea-logo.png",
    number: 6,
    age: 21,
    height: "189cm",
    weight: "78kg",
    goals: 12,
    assists: 9,
    appearances: 28,
    rating: "7.8",
    created_at: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Nicolas Jackson",
    position: "Forward",
    nationality: "Senegal",
    photo_url: "/chelsea-logo.png",
    number: 7,
    age: 22,
    height: "186cm",
    weight: "78kg",
    goals: 8,
    assists: 4,
    appearances: 26,
    rating: "7.1",
    created_at: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Mykhailo Mudryk",
    position: "Forward",
    nationality: "Ukraine",
    photo_url: "/chelsea-logo.png",
    number: 8,
    age: 23,
    height: "175cm",
    weight: "70kg",
    goals: 4,
    assists: 6,
    appearances: 24,
    rating: "6.9",
    created_at: new Date().toISOString(),
  },
  {
    id: 9,
    name: "Moisés Caicedo",
    position: "Midfielder",
    nationality: "Ecuador",
    photo_url: "/chelsea-logo.png",
    number: 9,
    age: 22,
    height: "178cm",
    weight: "73kg",
    goals: 1,
    assists: 3,
    appearances: 22,
    rating: "7.0",
    created_at: new Date().toISOString(),
  },
  {
    id: 10,
    name: "Reece James",
    position: "Defender",
    nationality: "England",
    photo_url: "/chelsea-logo.png",
    number: 10,
    age: 24,
    height: "179cm",
    weight: "91kg",
    goals: 1,
    assists: 2,
    appearances: 8,
    rating: "7.1",
    created_at: new Date().toISOString(),
  },
  {
    id: 11,
    name: "Levi Colwill",
    position: "Defender",
    nationality: "England",
    photo_url: "/chelsea-logo.png",
    number: 11,
    age: 20,
    height: "187cm",
    weight: "80kg",
    goals: 0,
    assists: 1,
    appearances: 16,
    rating: "6.9",
    created_at: new Date().toISOString(),
  },
  {
    id: 12,
    name: "Christopher Nkunku",
    position: "Forward",
    nationality: "France",
    photo_url: "/chelsea-logo.png",
    number: 12,
    age: 26,
    height: "175cm",
    weight: "70kg",
    goals: 2,
    assists: 1,
    appearances: 6,
    rating: "6.8",
    created_at: new Date().toISOString(),
  },
  {
    id: 13,
    name: "Malo Gusto",
    position: "Defender",
    nationality: "France",
    photo_url: "/chelsea-logo.png",
    number: 13,
    age: 20,
    height: "178cm",
    weight: "70kg",
    goals: 0,
    assists: 4,
    appearances: 18,
    rating: "7.0",
    created_at: new Date().toISOString(),
  },
  {
    id: 14,
    name: "Trevoh Chalobah",
    position: "Defender",
    nationality: "England",
    photo_url: "/chelsea-logo.png",
    number: 14,
    age: 24,
    height: "190cm",
    weight: "85kg",
    goals: 0,
    assists: 0,
    appearances: 5,
    rating: "6.5",
    created_at: new Date().toISOString(),
  },
  {
    id: 15,
    name: "Ben Chilwell",
    position: "Defender",
    nationality: "England",
    photo_url: "/chelsea-logo.png",
    number: 15,
    age: 27,
    height: "178cm",
    weight: "77kg",
    goals: 0,
    assists: 1,
    appearances: 6,
    rating: "6.7",
    created_at: new Date().toISOString(),
  },
  {
    id: 16,
    name: "Romeo Lavia",
    position: "Midfielder",
    nationality: "Belgium",
    photo_url: "/chelsea-logo.png",
    number: 16,
    age: 20,
    height: "181cm",
    weight: "70kg",
    goals: 0,
    assists: 0,
    appearances: 1,
    rating: "6.5",
    created_at: new Date().toISOString(),
  },
  {
    id: 17,
    name: "Robert Sánchez",
    position: "Goalkeeper",
    nationality: "Spain",
    photo_url: "/chelsea-logo.png",
    number: 17,
    age: 26,
    height: "197cm",
    weight: "88kg",
    goals: 0,
    assists: 0,
    appearances: 12,
    rating: "6.9",
    created_at: new Date().toISOString(),
  },
  {
    id: 18,
    name: "Enzo Maresca",
    position: "Manager",
    nationality: "Italy",
    photo_url: "/chelsea-logo.png",
    number: 0,
    age: 44,
    height: "180cm",
    weight: "75kg",
    goals: 0,
    assists: 0,
    appearances: 0,
    rating: "7.5",
    created_at: new Date().toISOString(),
  },
  {
    id: 19,
    name: "Liam Delap",
    position: "Forward",
    nationality: "England",
    photo_url: "/chelsea-logo.png",
    number: 9,
    age: 22,
    height: "185cm",
    weight: "80kg",
    goals: 2,
    assists: 1,
    appearances: 8,
    rating: "6.8",
    created_at: new Date().toISOString(),
  },
  {
    id: 20,
    name: "Joao Pedro",
    position: "Forward",
    nationality: "Brazil",
    photo_url: "/chelsea-logo.png",
    number: 20,
    age: 23,
    height: "182cm",
    weight: "75kg",
    goals: 3,
    assists: 2,
    appearances: 12,
    rating: "7.0",
    created_at: new Date().toISOString(),
  },
  {
    id: 21,
    name: "Dario Essugo",
    position: "Midfielder",
    nationality: "Portugal",
    photo_url: "/chelsea-logo.png",
    number: 14,
    age: 20,
    height: "175cm",
    weight: "70kg",
    goals: 0,
    assists: 1,
    appearances: 6,
    rating: "6.7",
    created_at: new Date().toISOString(),
  },
  {
    id: 22,
    name: "Jamie Gittens",
    position: "Forward",
    nationality: "England",
    photo_url: "/chelsea-logo.png",
    number: undefined,
    age: 20,
    height: "178cm",
    weight: "72kg",
    goals: 1,
    assists: 0,
    appearances: 4,
    rating: "6.6",
    created_at: new Date().toISOString(),
  },
];

export async function fetchRoster(): Promise<Player[]> {
  try {
    // First try to get real data from Football API
    console.log('Football API key available:', !!process.env.NEXT_PUBLIC_FOOTBALL_DATA_API_KEY);
    if (process.env.NEXT_PUBLIC_FOOTBALL_DATA_API_KEY) {
      try {
        console.log('Fetching real Chelsea squad data from API...');
        const apiPlayers = await fetchChelseaSquad();
        console.log('API response:', apiPlayers.length, 'players');
        if (apiPlayers.length > 0) {
          const transformedPlayers = await Promise.all(apiPlayers.map(transformPlayer));
          console.log(`Successfully fetched ${transformedPlayers.length} players from API`);
          return transformedPlayers;
        } else {
          console.log('No players returned from API, using fallback');
        }
      } catch (apiError) {
        console.error('Football API error, using fallback data:', apiError);
      }
    } else {
      console.log('No Football API key found, using fallback data');
    }

    // Use fallback data as primary source when API is not available
    console.log('Using fallback Chelsea squad data');
    return FALLBACK_SQUAD;
    
  } catch (error) {
    console.error('Error fetching roster:', error);
    // Return fallback data on error
    return FALLBACK_SQUAD;
  }
} 