import { supabase } from '@/lib/supabaseClient';
import { fetchChelseaFixtures, transformFixture } from './footballApi';

export interface Fixture {
  id: number;
  date: string;
  competition: string;
  opponent: string;
  opponent_logo?: string;
  home_or_away: 'home' | 'away';
  score?: string;
  venue?: string;
  status?: string;
  created_at: string;
}

// Fallback Chelsea fixtures data (2025/26 season - upcoming fixtures)
const FALLBACK_FIXTURES: Fixture[] = [
  {
    id: 1,
    date: "2025-08-16T14:00:00Z",
    competition: "Premier League",
    opponent: "Manchester City",
    opponent_logo: "https://crests.football-data.org/50.png",
    home_or_away: "away",
    score: undefined,
    venue: "Etihad Stadium",
    status: "SCHEDULED",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    date: "2025-08-23T16:30:00Z",
    competition: "Premier League",
    opponent: "West Ham United",
    opponent_logo: "https://crests.football-data.org/48.png",
    home_or_away: "home",
    score: undefined,
    venue: "Stamford Bridge",
    status: "SCHEDULED",
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    date: "2025-08-30T14:00:00Z",
    competition: "Premier League",
    opponent: "Crystal Palace",
    opponent_logo: "https://crests.football-data.org/52.png",
    home_or_away: "away",
    score: undefined,
    venue: "Selhurst Park",
    status: "SCHEDULED",
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    date: "2024-09-15T16:30:00Z",
    competition: "Premier League",
    opponent: "Bournemouth",
    opponent_logo: "https://crests.football-data.org/35.png",
    home_or_away: "home",
    score: "3-0",
    venue: "Stamford Bridge",
    status: "FT",
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    date: "2024-09-22T14:00:00Z",
    competition: "Premier League",
    opponent: "Aston Villa",
    opponent_logo: "https://crests.football-data.org/66.png",
    home_or_away: "away",
    score: "1-2",
    venue: "Villa Park",
    status: "FT",
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    date: "2024-09-29T16:30:00Z",
    competition: "Premier League",
    opponent: "Brighton & Hove Albion",
    opponent_logo: "https://crests.football-data.org/51.png",
    home_or_away: "home",
    score: "2-2",
    venue: "Stamford Bridge",
    status: "FT",
    created_at: new Date().toISOString(),
  },
  {
    id: 7,
    date: "2024-10-06T14:00:00Z",
    competition: "Premier League",
    opponent: "Fulham",
    opponent_logo: "https://crests.football-data.org/36.png",
    home_or_away: "away",
    score: "0-2",
    venue: "Craven Cottage",
    status: "FT",
    created_at: new Date().toISOString(),
  },
  {
    id: 8,
    date: "2024-10-20T16:30:00Z",
    competition: "Premier League",
    opponent: "Arsenal",
    opponent_logo: "https://crests.football-data.org/42.png",
    home_or_away: "home",
    score: "2-2",
    venue: "Stamford Bridge",
    status: "FT",
    created_at: new Date().toISOString(),
  },
  {
    id: 9,
    date: "2024-10-27T14:00:00Z",
    competition: "Premier League",
    opponent: "Brentford",
    opponent_logo: "https://crests.football-data.org/55.png",
    home_or_away: "away",
    score: "2-0",
    venue: "Gtech Community Stadium",
    status: "FT",
    created_at: new Date().toISOString(),
  },
  {
    id: 10,
    date: "2024-11-03T16:30:00Z",
    competition: "Premier League",
    opponent: "Newcastle United",
    opponent_logo: "https://crests.football-data.org/34.png",
    home_or_away: "home",
    score: "4-1",
    venue: "Stamford Bridge",
    status: "FT",
    created_at: new Date().toISOString(),
  },
  {
    id: 11,
    date: "2024-11-10T14:00:00Z",
    competition: "Premier League",
    opponent: "Tottenham Hotspur",
    opponent_logo: "https://crests.football-data.org/47.png",
    home_or_away: "away",
    venue: "Tottenham Hotspur Stadium",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 12,
    date: "2024-11-24T16:30:00Z",
    competition: "Premier League",
    opponent: "Manchester United",
    opponent_logo: "https://crests.football-data.org/33.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 13,
    date: "2024-12-01T14:00:00Z",
    competition: "Premier League",
    opponent: "Liverpool",
    opponent_logo: "https://crests.football-data.org/40.png",
    home_or_away: "away",
    venue: "Anfield",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 14,
    date: "2024-12-08T16:30:00Z",
    competition: "Premier League",
    opponent: "Everton",
    opponent_logo: "https://crests.football-data.org/45.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 15,
    date: "2024-12-15T14:00:00Z",
    competition: "Premier League",
    opponent: "Wolverhampton Wanderers",
    opponent_logo: "https://crests.football-data.org/39.png",
    home_or_away: "away",
    venue: "Molineux Stadium",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 16,
    date: "2024-12-22T16:30:00Z",
    competition: "Premier League",
    opponent: "Nottingham Forest",
    opponent_logo: "https://crests.football-data.org/65.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 17,
    date: "2024-12-26T15:00:00Z",
    competition: "Premier League",
    opponent: "Burnley",
    opponent_logo: "https://crests.football-data.org/44.png",
    home_or_away: "away",
    venue: "Turf Moor",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 18,
    date: "2024-12-29T16:30:00Z",
    competition: "Premier League",
    opponent: "Luton Town",
    opponent_logo: "https://crests.football-data.org/1359.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 19,
    date: "2025-01-05T16:30:00Z",
    competition: "Premier League",
    opponent: "Sheffield United",
    opponent_logo: "https://crests.football-data.org/49.png",
    home_or_away: "away",
    venue: "Bramall Lane",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 20,
    date: "2025-01-12T16:30:00Z",
    competition: "Premier League",
    opponent: "West Ham United",
    opponent_logo: "https://crests.football-data.org/48.png",
    home_or_away: "away",
    venue: "London Stadium",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 21,
    date: "2025-01-19T16:30:00Z",
    competition: "Premier League",
    opponent: "Crystal Palace",
    opponent_logo: "https://crests.football-data.org/52.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 22,
    date: "2025-02-02T16:30:00Z",
    competition: "Premier League",
    opponent: "Bournemouth",
    opponent_logo: "https://crests.football-data.org/35.png",
    home_or_away: "away",
    venue: "Vitality Stadium",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 23,
    date: "2025-02-09T16:30:00Z",
    competition: "Premier League",
    opponent: "Aston Villa",
    opponent_logo: "https://crests.football-data.org/66.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 24,
    date: "2025-02-23T16:30:00Z",
    competition: "Premier League",
    opponent: "Brighton & Hove Albion",
    opponent_logo: "https://crests.football-data.org/51.png",
    home_or_away: "away",
    venue: "Amex Stadium",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 25,
    date: "2025-03-02T16:30:00Z",
    competition: "Premier League",
    opponent: "Fulham",
    opponent_logo: "https://crests.football-data.org/36.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 26,
    date: "2025-03-09T16:30:00Z",
    competition: "Premier League",
    opponent: "Arsenal",
    opponent_logo: "https://crests.football-data.org/42.png",
    home_or_away: "away",
    venue: "Emirates Stadium",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 27,
    date: "2025-03-16T16:30:00Z",
    competition: "Premier League",
    opponent: "Brentford",
    opponent_logo: "https://crests.football-data.org/55.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 28,
    date: "2025-03-30T16:30:00Z",
    competition: "Premier League",
    opponent: "Newcastle United",
    opponent_logo: "https://crests.football-data.org/34.png",
    home_or_away: "away",
    venue: "St James' Park",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 29,
    date: "2025-04-06T16:30:00Z",
    competition: "Premier League",
    opponent: "Tottenham Hotspur",
    opponent_logo: "https://crests.football-data.org/47.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 30,
    date: "2025-04-13T16:30:00Z",
    competition: "Premier League",
    opponent: "Manchester United",
    opponent_logo: "https://crests.football-data.org/33.png",
    home_or_away: "away",
    venue: "Old Trafford",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 31,
    date: "2025-04-20T16:30:00Z",
    competition: "Premier League",
    opponent: "Liverpool",
    opponent_logo: "https://crests.football-data.org/40.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 32,
    date: "2025-04-27T16:30:00Z",
    competition: "Premier League",
    opponent: "Everton",
    opponent_logo: "https://crests.football-data.org/45.png",
    home_or_away: "away",
    venue: "Goodison Park",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 33,
    date: "2025-05-04T16:30:00Z",
    competition: "Premier League",
    opponent: "Wolverhampton Wanderers",
    opponent_logo: "https://crests.football-data.org/39.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 34,
    date: "2025-05-11T16:30:00Z",
    competition: "Premier League",
    opponent: "Nottingham Forest",
    opponent_logo: "https://crests.football-data.org/65.png",
    home_or_away: "away",
    venue: "City Ground",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 35,
    date: "2025-05-18T16:30:00Z",
    competition: "Premier League",
    opponent: "Burnley",
    opponent_logo: "https://crests.football-data.org/44.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 36,
    date: "2025-05-25T16:30:00Z",
    competition: "Premier League",
    opponent: "Luton Town",
    opponent_logo: "https://crests.football-data.org/1359.png",
    home_or_away: "away",
    venue: "Kenilworth Road",
    status: "NS",
    created_at: new Date().toISOString(),
  },
  {
    id: 37,
    date: "2025-06-01T16:30:00Z",
    competition: "Premier League",
    opponent: "Sheffield United",
    opponent_logo: "https://crests.football-data.org/49.png",
    home_or_away: "home",
    venue: "Stamford Bridge",
    status: "NS",
    created_at: new Date().toISOString(),
  },
];

export async function fetchFixtures(): Promise<Fixture[]> {
  try {
    // First try to get real data from Football API
    if (process.env.NEXT_PUBLIC_FOOTBALL_DATA_API_KEY) {
      try {
        const apiFixtures = await fetchChelseaFixtures();
        if (apiFixtures.length > 0) {
          const transformedFixtures = await Promise.all(apiFixtures.map(fixture => transformFixture(fixture)));
          return transformedFixtures;
        }
      } catch (apiError) {
        console.error('Football API error, falling back to database:', apiError);
      }
    }

    // Try to get data from Supabase
    const { data, error } = await supabase
      .from('fixtures')
      .select('*')
      .order('date', { ascending: true });
    
    if (!error && data && data.length > 0) {
      return data as Fixture[];
    }
    
    // If no data in Supabase, return fallback data
    return FALLBACK_FIXTURES;
    
  } catch (error) {
    console.error('Error fetching fixtures:', error);
    // Return fallback data on error
    return FALLBACK_FIXTURES;
  }
} 